# Data Preperation

## Objective
Prepare the cleaned dataset for machine learning without introducing data leakage

# Import Libraries and load data

In [33]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Preprocessing
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

df = pd.read_csv("../data/processed/cleveland_clean.csv")

df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,1,145,233,1,2,150,0,2.3,3,0,6,0
1,67,1,4,160,286,0,2,108,1,1.5,2,3,3,1
2,67,1,4,120,229,0,2,129,1,2.6,2,2,7,1
3,37,1,3,130,250,0,0,187,0,3.5,3,0,3,0
4,41,0,2,130,204,0,2,172,0,1.4,1,0,3,0

# Seperate Feature and Target

## Features

In [34]:
X = df.drop(columns="target")
X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,1,145,233,1,2,150,0,2.3,3,0,6
1,67,1,4,160,286,0,2,108,1,1.5,2,3,3
2,67,1,4,120,229,0,2,129,1,2.6,2,2,7
3,37,1,3,130,250,0,0,187,0,3.5,3,0,3
4,41,0,2,130,204,0,2,172,0,1.4,1,0,3

In [35]:
X.shape

(303, 13)

## Target

In [36]:
y = df["target"]
y.head()

0    0
1    1
2    1
3    0
4    0
Name: target, dtype: int64

In [37]:
y.shape

(303,)

# Feature Types

- Dividing features to numerical andcategorical, as they need different preprocessings

## Numerical Features

In [38]:
numerical_features = [
    "age",
    "trestbps",
    "chol",
    "thalach",
    "oldpeak"
]
numerical_features

['age', 'trestbps', 'chol', 'thalach', 'oldpeak']

## Categorical Features

In [39]:
categorical_features = [
    "sex",
    "cp",
    "fbs",
    "restecg",
    "exang",
    "slope",
    "ca",
    "thal"
]
categorical_features

['sex', 'cp', 'fbs', 'restecg', 'exang', 'slope', 'ca', 'thal']

# Train/Test Split

In [40]:
X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state=42,
    stratify=y
)

## Verify

In [41]:
print(X_train.shape)
print(X_test.shape)

print(y_train.value_counts())
print(y_test.value_counts())

(242, 13)
(61, 13)
target
0    131
1    111
Name: count, dtype: int64
target
0    33
1    28
Name: count, dtype: int64

# Preprocessing Pipeline

In [42]:
# Numerical pipeline
numerical_pipeline = Pipeline(
    steps=[
        ("scaler", StandardScaler())
    ]
)

# Categorical pipeline - leave them as they are, as they are already int-coded
categorical_pipeline = "passthrough"


# Combination
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numerical_pipeline, numerical_features),
        ("cat", categorical_pipeline, categorical_features)
    ]
)

# Fitting Training Data

In [43]:
preprocessor.fit(X_train)

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('scaler', StandardScaler())]),
                                 ['age', 'trestbps', 'chol', 'thalach',
                                  'oldpeak']),
                                ('cat', 'passthrough',
                                 ['sex', 'cp', 'fbs', 'restecg', 'exang',
                                  'slope', 'ca', 'thal'])])

# Transform

In [44]:
X_train_processed = preprocessor.transform(X_train)
X_train_processed.shape

(242, 13)

In [45]:
X_test_processed = preprocessor.transform(X_test)
X_test_processed.shape

(61, 13)

# Data Preperation Summary

- Loaded the cleaned dataset.
- Split features and target.
- Identified numerical and categorical variables.
- Performed an 80/20 stratified train-test split.
- Standardized numerical features using StandardScaler.
- Left categorical features unchanged.
- Fit the preprocessing pipeline using only the training data.
- Transformed both training and testing datasets.